language: node_js
node_js:
  - 8.5.0
sudo: required
cache:
  - yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add greenkeeper-lockfile@1 # Greenkeeper lockfile support
install:
  - yarn install
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn test
after_script:
  - greenkeeper-lockfile-upload
notifications:
  email: false
  slack:
    secure: hwppInk7LGgRVzPNJzxQ/5ZQrU+Cv8gjFMDI1zXCZMQ+PT+keqoh+0zVYUjllQ23+gCaHRnzdjPSPp8WtQ/TkTHCvJypoczrb5Cy9eU7K9epHv+n2KdUDpT9x4ijmXe+pg0doU4wUcFEQjuB1soAbC4FdQdOhOh2zjmgY/Y+0wlbwNAVSEkDYpw9ddwukZ7kltW9H440M3Cis7utzFr1gdTtVQOHfv24Hh7R6GBFErkWSzI8vp9FGdzGR2cpJ+f2lCxqCq0isB/xFQuWhEJGqoU8ZaDfgGgMS3HGt3xEYQD7rpoGkptMuO15oT7EE4rYtX/CjuAu/HCvcEgWSuq57Hs4u2gVTRdaFWWOl3iL1445KCgjYm+jrurljPYq7pj7TMe1w2yfGQn1DJQuUznBdbebfVNhlr+2SWMHrOA1N4dLOoVbikntn/KRIXyhQbpz/anO5f90yHUFD9CxCrhPcey5RAYNOQRHjcPWdPJTp/J6Ug1JxDdP3WEFfxcw6M81rNj/4L99Wojbh/Zl4b0GG9NLZ6K3zWVcxmB+U2S7y91KJZ6iSZd8cFxwEc6zt7pJebDedinQIVwO+wDpl8dSZCvderr8491b2v/Sz277Lq8WUJ8+VCserrnOdx/XGU3pFAXfk4C4HEzkdUsN+qxQ6j+4PLyeZ2DFnBv1GgtUPOc=
