"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
/*
    Math base
 */
var RADIAN_BASE = 180;
var RADIAN_CONVERT = exports.RADIAN_CONVERT = Math.PI / RADIAN_BASE;

/*
    EXIF orientation codes
    - for reference, EXIF orientation codes available at http://sylvana.net/jpegcrop/exif_orientation.html
 */
var ORIENTATION_HORIZONTAL_REVERSED = exports.ORIENTATION_HORIZONTAL_REVERSED = 2;
var ORIENTATION_BOTH_REVERSED = exports.ORIENTATION_BOTH_REVERSED = 3;
var ORIENTATION_VERTICAL_REVERSED = exports.ORIENTATION_VERTICAL_REVERSED = 4;
var ORIENTATION_FLIPPED_AND_ROTATED = exports.ORIENTATION_FLIPPED_AND_ROTATED = 5;
var ORIENTATION_ROTATED_RIGHT = exports.ORIENTATION_ROTATED_RIGHT = 6;
var ORIENTATION_HORIZONTAL_FLIPPED_AND_ROTATED = exports.ORIENTATION_HORIZONTAL_FLIPPED_AND_ROTATED = 7;
var ORIENTATION_ROTATED_LEFT = exports.ORIENTATION_ROTATED_LEFT = 8;
;

var _temp = function () {
    if (typeof __REACT_HOT_LOADER__ === 'undefined') {
        return;
    }

    __REACT_HOT_LOADER__.register(RADIAN_BASE, "RADIAN_BASE", "app/constants.js");

    __REACT_HOT_LOADER__.register(RADIAN_CONVERT, "RADIAN_CONVERT", "app/constants.js");

    __REACT_HOT_LOADER__.register(ORIENTATION_HORIZONTAL_REVERSED, "ORIENTATION_HORIZONTAL_REVERSED", "app/constants.js");

    __REACT_HOT_LOADER__.register(ORIENTATION_BOTH_REVERSED, "ORIENTATION_BOTH_REVERSED", "app/constants.js");

    __REACT_HOT_LOADER__.register(ORIENTATION_VERTICAL_REVERSED, "ORIENTATION_VERTICAL_REVERSED", "app/constants.js");

    __REACT_HOT_LOADER__.register(ORIENTATION_FLIPPED_AND_ROTATED, "ORIENTATION_FLIPPED_AND_ROTATED", "app/constants.js");

    __REACT_HOT_LOADER__.register(ORIENTATION_ROTATED_RIGHT, "ORIENTATION_ROTATED_RIGHT", "app/constants.js");

    __REACT_HOT_LOADER__.register(ORIENTATION_HORIZONTAL_FLIPPED_AND_ROTATED, "ORIENTATION_HORIZONTAL_FLIPPED_AND_ROTATED", "app/constants.js");

    __REACT_HOT_LOADER__.register(ORIENTATION_ROTATED_LEFT, "ORIENTATION_ROTATED_LEFT", "app/constants.js");
}();

;